#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin

cmdline=$(awk '{print $(NF)}' /proc/cmdline)

if [ -d /etc/runit/runsvdir/$cmdline ];then
  default=$cmdline
else
  default=default
fi
if [ "$default" == "single" ];then
  /etc/runit/rc/rc.single
else
  /etc/runit/rc/rc.multi
fi
runsvchdir $default

# Start any legacy (one-time) daemons
. /etc/rc.conf
for daemon in $DAEMONS;do
  /etc/init.d/$daemon start
done

exec env - PATH=$PATH \
runsvdir -P /service 'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................'
